# name: Deploy WordPress

# on:
#   push:
#     branches:
#       - main  # Adjust this to your default branch

# jobs:
#   deploy:
#     runs-on: ubuntu-latest  # Use an appropriate runner

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up SSH
#         uses: webfactory/ssh-agent@v0.5.3
#         with:
#           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#       - name: Deploy using Docker Compose
#         run: |
#           ssh ${{ secrets.SSH_USERNAME }}@your-server-ip "cd /path/to/your/compose/files && docker-compose pull && docker-compose up -d"

# name: Deploy_WordPress

# on:
#   push:
#     branches: [main]

# jobs:
#   Build:
#     runs-on: self-hosted

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@main

#       - name: Run Build
#         run: cd /home/asit/wordpress && docker-compose up -d

name: Deploy_WordPress

on:
  push:
    branches: [main]

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - name: User
        run: whoim
        
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Set up environment variables
        run: |
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> $GITHUB_WORKSPACE/.env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> $GITHUB_WORKSPACE/.env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> $GITHUB_WORKSPACE/.env

      - name: Display environment variables
        run: cat $GITHUB_WORKSPACE/.env

      - name: Run Build
        run: |
          cd $GITHUB_WORKSPACE  # Move to the repository root
          docker-compose up -d
