# name: Deploy WordPress

# on:
#   push:
#     branches:
#       - main  # Adjust this to your default branch

# jobs:
#   deploy:
#     runs-on: ubuntu-latest  # Use an appropriate runner

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up SSH
#         uses: webfactory/ssh-agent@v0.5.3
#         with:
#           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#       - name: Deploy using Docker Compose
#         run: |
#           ssh ${{ secrets.SSH_USERNAME }}@your-server-ip "cd /path/to/your/compose/files && docker-compose pull && docker-compose up -d"

name: Deploy_WordPress

on:
  push:
    branches: [main]

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      # - name: Set up environment variables
      #   env:
      #     MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      #     MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      #     MYSQL_USER: ${{ secrets.MYSQL_USER }}
      #   run: echo "MYSQL_PASSWORD=${MYSQL_PASSWORD}" >> .env && echo "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}" >> .env && echo "MYSQL_USER=${MYSQL_USER}" >> .env
     
      - name: Set up environment variables
        run: echo "MYSQL_PASSWORD=<span class="math-inline">\{MYSQL\_PASSWORD\}" \>\> \.env && echo "MYSQL\_ROOT\_PASSWORD\=</span>{MYSQL_ROOT_PASSWORD}" >> .env && echo "MYSQL_USER=${MYSQL_USER}" >> .env
      
      - name: Run Build
        run: docker-compose up -d

      
