name: Deploy_WordPress

on:
  push:
    branches: [main]

jobs:
  Build:
    runs-on: self-hosted

    steps:

      # - name: Change ownership of directories
      #   run: |
      #     sudo chown -R runner:runner $GITHUB_WORKSPACE/certbot-etc
      #     sudo chown -R runner:runner $GITHUB_WORKSPACE/wordpress
      #     sudo chown -R runner:runner $GITHUB_WORKSPACE/dbdata

      # - name: Clear workspace
      #   run: rm -rf $GITHUB_WORKSPACE/*
        
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Set up environment variables
        run: |
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> $GITHUB_WORKSPACE/.env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> $GITHUB_WORKSPACE/.env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> $GITHUB_WORKSPACE/.env

      - name: Display environment variables
        run: cat $GITHUB_WORKSPACE/.env

      - name: Run Build
        run: |
          cd $GITHUB_WORKSPACE  # Move to the repository root
          docker-compose up -d
